### ISSUE TITLE
Reg Summary for Long text/documents

### ISSUE THREAD

**Issue by apvarana** [balakreshnan/Samples2023#1]
Hi @balakreshnan . Thanks for the samples, they are quite helpful. For the sample formreclongtext.md, The summary generated is around 3/4 lines for document of 5 pages, is there any config which can generate summary with reasonable length.

And also like Azure AI summarization (Language Analytics) capability, will there be Extractive and Abstractive?

**Comment by balakreshnan** [comment]
Hi Aparna, It's more Extractive. For larger summary please use the max_token and increase according to your requirements.

**Comment by balakreshnan** [comment]
Hi Aparna, It's more Extractive. For larger summary please use the max_token and increase according to your requirements.
